### ISSUE TITLE
Error Running main.py [BUG]

### ISSUE THREAD

**Issue by animeworld0310** [Dexter2389/whatsapp-backup-chat-viewer#28]
Showing the below error :

Traceback (most recent call last):
  File "C:\Users\yamru\whatsapp-backup-chat-viewer\main.py", line 160, in <module>
    chats_to_txt_formatted(
  File "C:\Users\yamru\whatsapp-backup-chat-viewer\src\exports\to_txt.py", line 150, in chats_to_txt_formatted
    file.write(f"{chat_title_details}\n\n{messages}")
  File "C:\Program Files\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f601' in position 17: character maps to <undefined>

**Comment by menotuu** [comment]
and for me
PS D:\Desktop\backup-chat-viewer-main> python main.py -mdb msgstore.db -wdb wa.db -o output
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "D:\Desktop\backup-chat-viewer-main\main.py", line 160, in <module>
    chats_to_txt_formatted(
  File "D:\Desktop\backup-chat-viewer-main\src\exports\to_txt.py", line 150, in chats_to_txt_formatted
    file.write(f"{chat_title_details}\n\n{messages}")
  File "C:\Users\Packy\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\ue40d' in position 777: character maps to <undefined>
