### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nadun84** [Dexter2389/whatsapp-backup-chat-viewer#29]
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-16: character maps to <undefined>

What is the meaning of this

**Comment by Nadun84** [comment]
D:\whatsapp-backup-chat-viewer>python main.py -mdb msgstore.db -wdb wa.db -o output
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "D:\whatsapp-backup-chat-viewer\main.py", line 160, in <module>
    chats_to_txt_formatted(
  File "D:\whatsapp-backup-chat-viewer\src\exports\to_txt.py", line 150, in chats_to_txt_formatted
    file.write(f"{chat_title_details}\n\n{messages}")
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-16: character maps to <undefined>
